version: "3"
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - 8000:80
    volumes:
      - /root/wordpress/html:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=123456789  
    depends_on:
       - db  
    
       
    
 db:
     image: mysql:8.0
     container_name: mysql
     restart: always
     volumes:
       - /root/wordpress/mysql:/var/lib/mysql
     environment:
       - MYSQL_DATABASE=wordpress
       - MYSQL_USER=wordpress
       - MYSQL_PASSWORD=123456789
       - MYSQL_ROOT_PASSWORD=jqemAufxrjkjhgghgpu
       
